# Generated by Django 5.2.1 on 2026-05-06 13:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Genealogy',
            fields=[
                ('genealogy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_genealogies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'genealogy',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('death_year', models.PositiveIntegerField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, default='')),
                ('genealogy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.genealogy')),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('marriage_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('spouse1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_spouse1', to='app.member')),
                ('spouse2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_spouse2', to='app.member')),
            ],
            options={
                'db_table': 'marriage',
            },
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('pk', models.CompositePrimaryKey('parent_id', 'child_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother')], max_length=10)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='app.member')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_links', to='app.member')),
            ],
            options={
                'db_table': 'parent_child',
            },
        ),
        migrations.CreateModel(
            name='GenealogyUser',
            fields=[
                ('genealogy_user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('genealogy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='app.genealogy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'genealogy_user',
                'constraints': [models.UniqueConstraint(fields=('user', 'genealogy'), name='uq_genealogy_user_user_genealogy')],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['name'], name='idx_member_name'),
        ),
        migrations.RunSQL(
            sql="CREATE INDEX idx_member_name_prefix ON member(name(10));",
            reverse_sql="DROP INDEX idx_member_name_prefix ON member;",
        ),
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.CheckConstraint(condition=models.Q(('spouse1', models.F('spouse2')), _negated=True), name='chk_spouse_not_same'),
        ),
        migrations.AddIndex(
            model_name='parentchild',
            index=models.Index(fields=['parent'], name='idx_parent'),
        ),
        migrations.AddIndex(
            model_name='parentchild',
            index=models.Index(fields=['child'], name='idx_child'),
        ),
        migrations.AddIndex(
            model_name='parentchild',
            index=models.Index(fields=['parent', 'child'], name='idx_parent_child'),
        ),
        migrations.AddConstraint(
            model_name='parentchild',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='chk_parent_not_self'),
        ),
    ]
