# Generated by Django 5.2.1 on 2026-05-09 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberGenerationCache',
            fields=[
                ('member', models.OneToOneField(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='generation_cache', serialize=False, to='app.member')),
                ('generation', models.PositiveIntegerField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('genealogy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_caches', to='app.genealogy')),
            ],
            options={
                'db_table': 'member_generation_cache',
                'indexes': [models.Index(fields=['genealogy', 'generation'], name='idx_mgc_genealogy_generation')],
            },
        ),
    ]
